config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get '/comments/new', :to => 'comments#new'
  get '/stats/index', :to => 'stats#index'
  get '/stats/show', :to => 'stats#show'
  get '/sprivia', :to => 'users#sprivia'
  get '/sign-in', :to => 'sessions#new'
  get '/sign-out', :to => 'sessions#destroy'
  post '/sign-in', :to => 'sessions#create'

  get '/posts/show', :to => 'posts#show'
  post '/posts/create', :to => 'posts#new'

  resources :users
  resources :posts
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments

    scope :new_posts, -> { where('DATE(created_at) = ?', Date.today)}
end

app/models/session.rb
class Session < ApplicationRecord
    belongs_to :user
end

app/models/stat.rb
class Stat < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :stats
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy

    has_secure_password
    validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def index
        @comments = Comment.all
    end

    def new
        @comment = Comment.new
        @comment = Comment.new(post_id: params[:post_id])
        # @post = Post.find(params[:post_id])
    end

    def create
        @comment = Comment.new(comment_params)
        @comment.user_id = session[:user_id]
        # @post = Post.find(params[:comment][:id])
        if @comment.save
          flash[:notice] = "comment created."
          redirect_to "/posts/#{params[:post_id]}"
        else
          flash[:error] = "Error creating comment."
          redirect_to comments_new_path
        end
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to '/posts'
    end

    def comment_params
        params.require(:comment).permit(:post_id, :user_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all
        @posts = Post.includes(:comments).order("created_at DESC").limit(5)
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def edit
        @post = Post.find(params[:id])
    end

    def create
        @post = Post.create(post_params)
        @post.user_id = session[:user_id]
        if @post.save
            flash[:notice] = "Post created!"
            redirect_to posts_path
        else
            flash[:error] = "Post not created!"
            render :new
        end
    end

    def update
        post = Post.find(params[:id])
        post.update(post_params)
        flash[:notice] = "Post Updated!"
        redirect_to '/posts'
    end

    def destroy
        post = Post.find(params[:id]).destroy
        flash[:notice] = "Post deleted."
        redirect_to posts_path 
    end

    def validate
        if session[:user_id] != @post.user_id
            flash[:notice] = "You can't edit this post"
            redirect_to posts_path
        end
    end
    
    def post_params
        params.require(:post).permit(:entry, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "#{@user.name} is logged in!"
      redirect_to @user, notice: "#{@user.name} is logged in!"
    else
      flash[:notice] = "Login Failed"
      redirect_to '/sessions/new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/', notice: "Logged out!"
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.create(user_params)
        if @user.save
        flash[:notice] = 'Successfully Created!'
        redirect_to '/sign-in'
        else
        flash[:notice] = 'Email Already Exists!'
        render :new 
      end
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    flash[:notice] = "Info Updated!"
    redirect_to current_user
  end 

  def sprivia
    @user = current_user
  end

  def destroy
    @user = User.find(params[:id]).destroy
    flash[:notice] = 'User deleted!'
    redirect_to '/'
  end

  private

  def user_params 
    params.require(:user).permit(:name, :email, :nickname, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment_form.html.erb
<div id="comment-form">
    <%= form_for @comment do |f| %>
        <p>
            <%= f.label :body %>
            <%= f.text_area :body, placeholder: "Enter Comment...", class: "text-area" %>
            <%= f.hidden_field :post_id %>
        </p>
        <p>
            <%= f.submit %>
        </p>
    <% end %>
</div>

app/views/comments/edit.html.erb
<%= render "comment_form"%>

app/views/comments/new.html.erb
<body id="comment_body_background">
    <div>
        <%= link_to "Profile", users_path, {class: 'post_link'} %>
    </div>
    <div id="comment_parent">
        <div id="comment_child">
            <div id="parent_comment_div">
                <h1 id="comment_title">POST YOUR COMMENTS!</h1>
                <%= render "comment_form", {class: 'text_box'}%>
            </div>
        </div>
    </div>
</body> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="apple-touch-icon" sizes="57x57" href="/images/favicon.ico/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/favicon.ico/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/favicon.ico/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/favicon.ico/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/favicon.ico/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/favicon.ico/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/favicon.ico/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/favicon.ico/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/favicon.ico/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/images/favicon.ico/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon.ico/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/images/favicon.ico/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon.ico/favicon-16x16.png">
    <link rel="manifest" href="/images/favicon.ico/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <style>a {text-decoration: none;} </style>
    <title>Sprivia</title>
    <link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:notice] if flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <p>
        <%= f.label :entry %>
        <%= f.text_area :entry, class: "text-area" %>
    </p>
    
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/posts/_post_form.html.erb
<%= form_for @post do |f| %>
    <p>
        <%= f.label :entry %>
        <%= f.text_area :entry, placeholder: "Enter Text...", class: "text-area" %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/posts/edit.html.erb
<body id="background">
    <div id="posts_edit_page">
        <div id="canvas_div">
            <div id="post_edit_parent">
                <h1 id="edit_post_title">UPDATE YOUR POST!</h1>    
                <%= render "post_form"%>
            </div>
        </div>
    </div>
</body>

app/views/posts/index.html.erb
<body id="posts">
    <div id="link_to_menu">
        <%= link_to 'Sprivia', sprivia_path, {method: :get, class: 'link'}%>
        <%= link_to 'Log Out', '/', {method: :get, class: 'link'}%>
    </div>
    <div id="parent_container">
        <div id="blog_posts_container">
            <div id="blog_posts">
                <h1 id="create_post_heading">CREATED POSTS</h1>
                <p id="click_to_add_comment">Click on post to view or add comments</p>
                <p>
                    <%= link_to new_post_path do %>
                        <%= image_tag "/images/post-img.png", alt: 'a pencil writing on paper' %>
                    <% end %>
                </p>
            </div>
            </br>
            <div id='posts_index'>
                <% @posts.reverse.each do |post| %>
                    <li class="all_posts">
                        <span><h3>Post:</h3> <h4><%= link_to(post.entry, post) %></h4> </span>
                        <% if post.user %>
                            <span><h3>By:</h3> <h4><%= post.user.name %></h4>  </span>
                        <% end %>
                    </li>
                <% end %>
            </div>
        </div>
    </div>
</body>

app/views/posts/new.html.erb
<body id="background">
    <div>
        <%= link_to "All Posts", posts_path, {class: 'post_link'} %>
    </div>
    <div id="post_new_page">
        <div id="canvas_div">
            <div id="post_form_parent">
                <h1 id="post_title">POST YOUR THOUGHTS!</h1>
                <%= render "post_form", {class: 'text_box'}%>
            </div>
        </div>
    </div>
</body>

app/views/posts/show.html.erb
<body id="post_show_body">
    <div id="post_show_div_parent">
        <div id="post_border_box">
            <span><h3>Post:</h3> <h4><%= @post.entry %></h4></span>
            </br>
            <span><h3>Posted by:</h3> <h4><%= @post.user.name %></h4></span>
        </div>
        </br>
        <div id="comment_div">
            <% @post.comments.each do |c| %>
            <span><h3>Comment:</h3> <h4><%= c.body %></h4></span>
            <% end %>
        </div>
    </div>

    <nav id="post_nav">
        <div id="post_links">
            <%= link_to("Edit Post", edit_post_path(@post), {class: 'link'}) %>
            <%= link_to("Delete Post", @post, {method: 'delete', class: 'link'}) %>
            <%= link_to("Add Comment", new_comment_path(post_id: @post.id), {class: 'link'})%>
            <%= link_to("All Posts", posts_path, {method: :get, class: 'link'})%>
        </div>
    </nav>
</body>

app/views/stats/index.html.erb
<h1>Stats#index</h1>
<p>Find me in app/views/stats/index.html.erb</p>

app/views/stats/show.html.erb
<h1>Stats#show</h1>
<p>Find me in app/views/stats/show.html.erb</p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name, {class: 'label'} %>
  <%= f.text_field :name, {required: true, class: 'field'} %>
  <%= f.label :email, {class: 'label'} %>
  <%= f.text_field :email, {required: true, class: 'field'} %>
  <%= f.label :nickname, {class: 'label'} %>
  <%= f.text_field :nickname, {required: true, class: 'field'} %>
  <%= f.label :password, {class: 'label'} %>
  <%= f.password_field :password, {required: true, class: 'field'} %>
  <%= f.submit class: 'button' %>
<% end %>

app/views/users/edit.html.erb
<div class="background">
    <nav id="edit_nav">
        <div id="edit_links">
            <%= link_to 'Log Out', '/', {method: :get, class: 'link'}%>
            <%= link_to 'Profile', @user, {class: 'link'}%>
        </div>
    </nav>
    <h1 id="update_info">EDIT ACCOUT!</h1>
    <div id="edit_user">
        <%= render 'form', user: @user %>  
    </div>
    <div id="parent_anchor_man">
        <img id="anchor_man" src="/images/Are_you_sure.gif">
    </div>
</div>

app/views/users/index.html.erb
<div class="index">
    <h1 id="app_name">SPRIVIA</h1>
    <nav id="nav_menu">
        <ul>
            <li><a href="/users/new?">REGISTER</a></li>
            <li><a href="/sessions/new">LOGIN</a></li>
        </ul>
    </nav>
</div>



<!-- prior button link to create user, unsure if going to use -->
<!-- <%= button_to 'Create Profile', new_user_path, {id:"user_btn", method: :get} %> -->

app/views/users/new.html.erb
<div class="background">
    <nav id="nav_menu_new">
        <ul id="new_user_1">
            <li class="sessions"><a href="/users">HOME</a></li>
        </ul>
    </nav>
    <h1 id="create">CREATE AN ACCOUNT!</h1>
    <div id="create_user">
        <%= render 'form', user: @user %>
    </div>
    <div id="parent_image_div">
        <div id="image_div">
            <img id="hockey" src="/images/hockey.png">
            <img id="basketball" src="/images/basketball.png">
            <img id="woman" src="/images/woman.png">
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="background">
    <div id="user_name_profile">
        <h1><strong><%= @user.name %></strong></h1>
    </div>
    <div id="user_nickname_profile">
        <h3><em><%= "Nickname: " + @user.nickname %></em></h3>
    </div>
    
    <div id="interactive_chart"></div>

    <div id="profile_menu">
        <%= link_to 'Log Out', '/', {method: :get, class: 'link'}%>
        <%= link_to 'Sprivia', sprivia_path, {method: :get, class: 'link'}%>
        <%= link_to 'Edit Info', edit_user_path, {class: 'link'}%>
        <%= link_to 'New Post', new_post_path, {class: 'link'}%>
    </div>
</div>

app/views/users/sprivia.html.erb
<body>
    <div class="background">
        <h1 id="title"><%= "SPRIVIA" %></h1>
        
            <div id="question_canvas">
                <div id="flex_container">
                    <h2 class="questions">Start the Game!</h2>
                </div> 
                <br>
                <div id="flex_container2">
                    <form class="answerSelections">
                        <!-- answer options will appear -->
                    </form>
                </div>
                <div id="score">
                    <span class="correct_score"></span>
                    <span class="incorrect_score"></span>
                </div>
            </div>
            
        <nav id="triv_game_nav">
            <div id="sprivia_game">
                <%= link_to 'Log Out', '/', {method: :get, class: 'link'}%>
                <%= link_to 'Profile', @user, {class: 'link'}%>
                <button id="start_game" class="link" onClick="nextQestion()">Next Question</button>
            </div>
        </nav>
    </div>
</body>